---
title: "About the Modeling"
author: "Aaron Rendahl and Beth Fisher"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{About The Modeling}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
## WeatheringTrends 
## The WeatheringTrends R package is designed to provide a tool for objective selection of parameters for the geochemical mass balance method used to quantify elemental enrichment or depletion of rock and soil (Brimhall & Dietrich 1987). For a mass balance to successfully quantify elemental mass change, the measured materials must meet two criteria: the parent material must be homogeneous prior to enrichment or depletion and the immobile element must be resistant to removal by chemical dissolution or physical mobility. The driving force for the development of WeatheringTrends was to objectively identify depletion or enrichment of bedrock, even when these signatures are muted by natural variability. The package is also designed so the user can compare the concentration of several possible immobile elements and determine which immobile elements are the best fit for each weathering system. 

## The input values for the model are elements measured in pulverized samples of rock and/or soil by methods such as Indcutively Coupled Plasma Mass Spectrometry (ICP-MS) or X-Ray Florescensce (XRF). The major and minor rock forming elements used in these analyses commonly include Na, Mg, Al, Si, K, Ca, Ti, Mn, Fe, P, Ba, Ce, Co, Cr, Cu, Hf, La, Nb, Nd, Ni, Pb, Rb, Sc, Sr, Th, V, Y, Zn, and Zr. Among these elements the possible immobile elements include Zr, Ti, Nb, Hf, V, Y, and sometimes Si. Major elements are commonly reported as a percent on an oxide basis (CaO, SiO2), and the minor elements are commonly reported in parts per million. For the purpose of the model the user may choose to normalize these, but this is computationally unnecessary to successfully model the weathering trends. To run the WeatheringTrends model, the y parameter requires a ratio of mobile to immobile elements. The x parameter is the depth below the ground surface where the specimen was sampled, where the ground surface = 0, and each depth can be a positive or negative number. 

## Model

$log(y_i) = m(x_i) + \epsilon_i$, where $\epsilon_i \sim N(0, s^2(x_i))$

$$
m(x) =
\begin{cases}
  r-c \text{, for } x < pd\\
  log\left(e^r - (e^r - e^{r-c}) \frac{d - x}{d - pd}\right) \text{, for } pd \geq x > d\\
  r \text{, for } x \geq d
\end{cases}
$$
  
$$
s(x) =
\begin{cases}
  s_1 \text{, for } x < pd\\
  s_2 - (s_2 - s_1) \frac{d - x}{d - pd} \text{, for } pd \geq x > d\\
  s_2 \text{, for } x \geq d
\end{cases}
$$

```{r, echo=FALSE, fig.width=8, fig.height=4}
p <- 0.25
d <- 8
c <- 1.5
s1 <- 0.25
s2 <- 0.3
r <- 1
xx <- c(0, seq(2, 8, len=21), 12)
fit <- WeatheringTrends:::getmsd(x=xx, p=p, d=8, c=c, s1=s1, s2=s2, r=r)
fit$x <- xx
fit <- within(fit,{
  lwr <- estimate - sd
  upr <- estimate + sd
})
par(mfrow=c(1,2), cex=0.8)
with(fit, {
  plot(x, estimate, type="l", ylab="log(y)", ylim=c(r-c-s1, r+s2), xaxt="n", yaxt="n", frame=FALSE)
  lines(x, lwr, lty=2)
  lines(x, upr, lty=2)
  ll <- 0.1
  arrows(x0=d+1,y0=r,y1=r+s2,code=3,len=ll)
  text(d+1, r+s2/2, expression(s[2]), pos=2)  
  arrows(x0=p*d-1,y0=r-c,y1=r-c+s1,code=3,len=ll)
  text(p*d-1, r-c+s1/2, expression(s[1]), pos=2)
  axis(1, c(p*d, d), labels=c("pd", "d"), las=1)
  axis(2, c(r-c, r), labels=c("r-c", "r"), las=1)
})
with(fit, {
  plot(x, exp(estimate), type="l", ylab="y", ylim=c(exp(r-c-s1), exp(r+s2)), xaxt="n", yaxt="n", frame=FALSE)
  lines(x, exp(lwr), lty=2)
  lines(x, exp(upr), lty=2)
  axis(1, c(p*d, d), labels=c("pd", "d"), las=1)
  axis(2, c(exp(r-c), exp(r)), labels=expression(e^(r-c), e^r), las=1)
})
```
## The model input, y, is a ratio of mobile:immoble element. As the model fits the set of element ratios along y, it finds the best fit for two segments of line and calculates the standard deviation at each line segment. We report the depth at each line break, which may represent the depth influence of processes that may deplete or enrich the elements. We also report the confidence interval at the deepest slope break.

## Where we define the variables as follows:
## d is the depth at the deepest slope break
## pd is the depth at the shallowest slope break, where p is a fraction of d
## r is the y value of the deepest slope break where 
## y = e^r and r = mobile:immobile
## r-c is the difference in y between the two slope breaks
## s is the standard deviation
